### ISSUE TITLE
Seems to be sending junk data and no other messages.

### ISSUE THREAD

**Issue by kevin-sumo** [SumoLogic/fluentd-kubernetes-sumologic#13]
I installed the fluentd logger unfortunately it only seems to be sending junk data. Sample message below.

{"timestamp":1486707244000,"error_class":"KeyError","error":"key not found: \"kubernetes\"","tag":"kube-apiserver","time":1486707243,"record":{"severity":"I","pid":"5","source":"panics.go:76","message":"GET /api/v1/namespaces/kube-system/endpoints/kube-controller-manager: (992.752µs) 200 [[kube-controller-manager/v1.5.2 (linux/amd64) kubernetes/08e0995/leader-election] 127.0.0.1:11711]","_sumo_metadata":{"log_format":"json","source":"k8s_kube-apiserver","category":"kubernetes/kube-apiserver"}},"message":"dump an error event: error_class=KeyError error=\"key not found: \\\"kubernetes\\\"\" tag=\"kube-apiserver\" time=1486707243 record={\"severity\"=>\"I\", \"pid\"=>\"5\", \"source\"=>\"panics.go:76\", \"message\"=>\"GET /api/v1/namespaces/kube-system/endpoints/kube-controller-manager: (992.752\\xC2\\xB5s) 200 [[kube-controller-manager/v1.5.2 (linux/amd64) kubernetes/08e0995/leader-election] 127.0.0.1:11711]\", \"_sumo_metadata\"=>{:log_format=>\"json\", :source=>\"k8s_kube-apiserver\", :category=>\"kubernetes/kube-apiserver\"}}"}

Can you tell me what might be causing these messages to be printed into Sumo? It looks like these errors from fluentd itself.

**Comment by stevezau** [comment]
Can you paste the log from the fluentd container on STDOUT/STDERR ?

Also, have you pulled the latest version?

Please provide more details on your configuration

**Comment by kevin-sumo** [comment]
Thanks Steve for taking a look. Here is the config. 

```
apiVersion: extensions/v1beta1 
kind: DaemonSet 
metadata: 
name: fluentd 
labels: 
app: fluentd 
version: v1 
spec: 
template: 
metadata: 
labels: 
name: fluentd 
spec: 
volumes: 
- name: pos-files 
emptyDir: {} 
- name: host-logs 
hostPath: 
path: /var/log/ 
- name: docker-logs 
hostPath: 
path: /var/lib/docker/containers 
containers: 
- image: sumologic/fluentd-kubernetes-sumologic:latest 
resources: 
limits: 
cpu: 50m 
memory: 100Mi 
requests: 
cpu: 30m 
memory: 70Mi 
name: fluentd 
imagePullPolicy: Always 
volumeMounts: 
- name: host-logs 
mountPath: /mnt/log/ 
readOnly: true 
- name: docker-logs 
mountPath: /var/lib/docker/containers 
readOnly: true 
- name: pos-files 
mountPath: /mnt/pos/ 
env: 
- name: COLLECTOR_URL 
valueFrom: 
secretKeyRef: 
name: sumologic 
key: collector-url 
--- 
apiVersion: v1 
data: 
collector-url: {{ sumologic_kubernetes_url|b64encode }} 
kind: Secret 
metadata: 
name: sumologic 
namespace: default 
type: Opaque
```

**Comment by fikander** [comment]
I'm having the same issue - 1000s of logs as above. I've disabled kube-apiserver log to prevent running out of space in sumo.
It's been deployed yesterday to kubernetes 1.5.2 based cluster, off the master of this repo.

Here's the manifest I used:
```
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: fluentd
  labels:
    app: fluentd
    version: v1
spec:
  template:
    metadata:
      labels:
        name: fluentd
    spec:
      volumes:
      - name: pos-files
        emptyDir: {}
      - name: host-logs
        hostPath:
          path: /var/log/
      - name: docker-logs
        hostPath:
          path: /var/lib/docker
      containers:
      - image: sumologic/fluentd-kubernetes-sumologic:latest
        name: fluentd
        imagePullPolicy: Always
        volumeMounts:
        - name: host-logs
          mountPath: /mnt/log/
          readOnly: true
        - name: docker-logs
          mountPath: /var/lib/docker/
          readOnly: true
        - name: pos-files
          mountPath: /mnt/pos/
        env:
        - name: COLLECTOR_URL
          valueFrom:
            secretKeyRef:
              name: sumologic
              key: collector-url
```
