### ISSUE TITLE
kubernetes deployment cronjob logs are not collected

### ISSUE THREAD

**Issue by turbohoje** [SumoLogic/fluentd-kubernetes-sumologic#98]
output from cronjobs is not delivered.  cron jobs are creating output, and the sumo daemonset pod is detecting these files e.g.

```2018-11-13 21:22:54 +0000 [info]: #0 following tail of /mnt/log/containers/ssl-monitor-svc-1537959420-v9bq2_infra-test_ssl-monitor-script-42e671eb0de33a6016afef8e64fee234219b055af7fd0a716e6ccaa7f336574b.log```

however the content of these files is not sent to sumologic.  

this was deployed with a chart with the following settings

```
sumologic:
  collectorUrl: ...==
  logFormat: text
  sourceName: '%{namespace}/%{pod}/%{container}'
  sourceCategoryPrefix: ' '
  sourceHost: '%{pod}'
  sourceCategoryReplaceDash: '-'
updateStrategy: RollingUpdate
tolerations:
  - operator: "Exists"
```
